.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "README" "" "June 2020" "" ""
Manage your basic survival resources like food and water for preparation of emergency times\. Keep track of costs and food calories\.
.
.P
Spend and stock wisely for the unexpected with Quaremain\.
.
.P
Available on GNU/Linux Ubuntu 20\.04 as a graphical desktop application\.
.
.SH "Version"
0\.8\.3
.
.SH "Status"
Unstable
.
.SH "Downloads"
.
.SS "Executables"
.
.IP "\(bu" 4
Self contained executable for Ubuntu 20\.04 and Xubuntu 20\.04\.
.
.IP "\(bu" 4
For Kubuntu and other Ubuntu 20\.04 flavors (run apt install libwebkit2gtk\-4\.0\-dev first)
.
.IP "\(bu" 4
https://github\.com/momozor/quaremain/releases/tag/0\.7\.8
.
.IP "" 0
.
.SH "Building"
.
.SS "Dependencies"
.
.P
For server
.
.IP "\(bu" 4
sbcl (or ccl from Clozure Common Lisp official website)
.
.IP "\(bu" 4
quicklisp (manually install and download from Quicklisp\'s official website)
.
.IP "\(bu" 4
sqlite3\-devel
.
.IP "\(bu" 4
zlib\-devel
.
.IP "" 0
.
.P
For client
.
.IP "\(bu" 4
gcc
.
.IP "\(bu" 4
make
.
.IP "\(bu" 4
pkg\-config
.
.IP "\(bu" 4
webkit2gtk3\-devel
.
.IP "" 0
.
.P
For server
.
.IP "\(bu" 4
sbcl (or ccl from Clozure Common Lisp official website)
.
.IP "\(bu" 4
quicklisp (manually install and download from Quicklisp\'s official website)
.
.IP "\(bu" 4
libsqlite3\-dev
.
.IP "\(bu" 4
zlib1g\-dev
.
.IP "" 0
.
.P
For client
.
.IP "\(bu" 4
build\-essential (for most make and C compilers dependencies)
.
.IP "\(bu" 4
pkg\-config
.
.IP "\(bu" 4
libwebkit2gtk\-4\.0\-dev
.
.IP "" 0
.
.SS "Ubuntu 18\.04"
For server
.
.IP "\(bu" 4
sbcl (or ccl from Clozure Common Lisp official website)
.
.IP "\(bu" 4
quicklisp (manually install and download from Quicklisp\'s official website)
.
.IP "\(bu" 4
libsqlite3\-dev
.
.IP "\(bu" 4
zlib1g\-dev
.
.IP "" 0
.
.P
For client
.
.IP "\(bu" 4
build\-essential (for most make and C compilers dependencies)
.
.IP "\(bu" 4
pkg\-config
.
.IP "\(bu" 4
libwebkit2gtk\-3\.0\-dev
.
.IP "" 0
.
.P
This project depends on submodule at https://github\.com/momozor/quaremain\-vue\-client
.
.P
Use \fBgit clone \-\-recursive https://github\.com/momozor/quaremain\fR to clone this project with the submodule automatically\.
.
.P
By default, Quaremain uses SBCL compiler to build a small sized self\-contained executable with the trade off of high\-memory usage\.
.
.P
If you prefer lower memory usage, use CCL (Clozure implementation) to build, but with the result of bigger executable\.
.
.P
Deployment tarball size shouldn\'t really matter, if you distribute it as a compressed archive\.
.
.P
By default, uses SBCL to compile\.
.
.P
Replace with make LISP=lx86cl64 to use CCL\.
.
.P
\fB$ make\fR
.
.P
To make the launcher as an executable\.
.
.P
\fB$ chmod a+x \./Quaremain\fR
.
.P
Run\.
.
.P
\fB$ \./Quaremain\fR
.
.SH "Testing"
\fB$ make test\fR
.
.SH "Distributing For End Users"
Currently, Quaremain is tested on OpenSUSE Tumbleweed and Ubuntu 20\.04 (Focal Fossa)\. You must build on similar target platform to make a working distributable self\-contained executable tarball archive\.
.
.P
In a nutshell, if you want to distribute a run\-out\-of\-the box Quaremain software for Ubuntu 20\.04, you must build Quaremain on Ubuntu 20\.04\. Same for OpenSUSE Tumbleweed\.
.
.P
To simplify this process, run:
.
.IP "\(bu" 4
\fB$ make ubuntu20\.04\-tarball\fR if you want to build for Ubuntu 20\.04
.
.IP "" 0
.
.P
or
.
.IP "\(bu" 4
\fB$ make opensusetumbleweed\-tarball\fR
.
.IP "" 0
.
.P
if you want to build for OpenSUSE Tumbleweed\.
.
.SH "Known Issues"
.
.IP "\(bu" 4
You always need to (slime\-cd) in SLIME to the project directory\. This should be resolved soon since it seems Deploy handles the relative path for the end executable automatically\. We can go back to use merge\-pathnames and current project directory if my assumption about Deploy is correct\.
.
.IP "" 0
.
.SH "Contributing and reporting issues"
If you want to report a bug, to discuss features, to ask questions, or to send improvement patches, please open an issue or pull request at https://github\.com/momozor/quaremain
.
.P
If you don\'t prefer to use Github, consider email me your questions or patches directly to skelic3@gmail\.com or momozor4@gmail\.com
.
.P
Quaremain uses git as the primary version control system\.
.
.P
The back\-end system is largely made in Common Lisp\.
.
.P
The front\-end system is mostly made with Vue + nodejs ecosystem, HTML5, CSS3 and Javascript\.
.
.SH "Maintainers"
.
.IP "\(bu" 4
Quaremain\'s back\-end project author & maintainer \- Momozor \fIhttps://github\.com/momozor\fR <skelic3@gmail\.com, momozor4@gmail\.com>
.
.IP "\(bu" 4
Quaremain\'s front\-end project author & maintainer \- j0sephh123 \fIhttps://github\.com/j0sephh123\fR
.
.IP "" 0
.
.SH "License"
This software is released under the GPL\-3\.0 or any later version\. Please see COPYING file for more details\.
