name: CI

on:
  push:
    branches: [ master, experimental ]
  pull_request:
    branches: [ master, experimental ]
      
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libsqlite3-dev zlib1g-dev build-essential pkg-config libwebkit2gtk-4.0-dev git automake libcurl4-openssl-dev
    - name: Install and setup for roswell (SBCL and rove)
      run: |
        git clone -b release https://github.com/roswell/roswell.git
        cd roswell
        sh bootstrap
        ./configure
        make
        sudo make install
        ros setup
        ros install rove
    - name: Copy checkout repo to $HOME/quicklisp/local-projects and $HOME/.roswell/local-projects
      run: |
        echo $HOME;
        cd ..;

        cp -r quaremain $HOME/.roswell/local-projects/quaremain;
        
    - name: Testing
      run: |
        cd $HOME/.roswell/local-projects/quaremain
        $HOME/.roswell/bin/rove quaremain.asd
        

    - name: Building executable
      run: |
        cd $HOME/quicklisp/local-projects/quaremain; make;
